### PR TITLE
Added 8 companies

### PR DESCRIPTION
**Pull request by SaxenaKartik**

### CODE REVIEW

**Comment by draco-malfoy** [comment]
@sakshiseth Kindly modify the _List.md_ file also, to reflect adding of these separate files in alphabetical order. Thank you.

**Comment by sakshiseth** [comment]
@draco-malfoy I checked it just now List.md is being updated alphabetically. Do I need to update it with the companies added by @SaxenaKartik ?

**Comment by draco-malfoy** [comment]
@sakshiseth Sorry for the bothering. This change request was intended for @SaxenaKartik

**Comment by draco-malfoy** [comment]
@SaxenaKartik Kindly modify the List.md file also, to reflect adding of these separate files in alphabetical order. Thank you.

**Comment by SaxenaKartik** [comment]
Alright I will do that

**Comment by SaxenaKartik** [comment]
I am added the necessary details in List.md 
Kindly review the changes

**Review by draco-malfoy — APPROVED** [review]

**Comment by draco-malfoy** [comment]
@SaxenaKartik Thank you for the contribution.

**Comment by draco-malfoy** [comment]
@all-contributors please add @SaxenaKartik for documentation.

**Pull request closed without merging**
