### PR TITLE
Company name Added and Few More Changes

### PR DESCRIPTION
**Pull request by ImagineZero0**
I have added many company names and also ordered the name in alphabetical order and also made some changes to how the link appeared and also placed all the Company_Name.md in a particular folder for better access.

### CODE REVIEW

**Comment by ImagineZero0** [comment]
Hey, @draco-malfoy I have added some changes..
please kindly review them..

**Comment by draco-malfoy** [comment]
@ImagineZero0 The files have been reorganized. Kindly make changes accordingly. Thank you.

**Comment by draco-malfoy** [comment]
The main file is now _List.md_ instead of _company_database.md_.

**Comment by ImagineZero0** [comment]
Ok @draco-malfoy, Thank you for the info. I will do the required changes

**Comment by ImagineZero0** [comment]
I have added another PR #65 as I had made some mistakes here, and added the company names in that PR. Please review that one...

**Pull request closed without merging**
