### PR TITLE
added 2 companies- Ansrsource & monocept

### PR DESCRIPTION
**Pull request by shivarajloni**
added 2 new companies to the list, 
1. Ansrsource pvt. Ltd.
2. Monocept 

both these companies are in software industry, computer software and e-learning companies, well known.

### CODE REVIEW

**Comment by shivarajloni** [comment]
@draco-malfoy hey, please review my PR, and let me know if any changes required!

thank you.

**Comment by draco-malfoy** [comment]
@shivarajloni Please modify the _Lisd.md_ file also according to the guidelines.

**Comment by shivarajloni** [comment]
@draco-malfoy please review the changes, and add hacktoberfest tags

thanks

**Review by draco-malfoy — APPROVED** [review]

**Comment by draco-malfoy** [comment]
@all-contributors please add @shivarajloni for documentation

**Pull request merged**
