### PR TITLE
Add dev company

### PR DESCRIPTION
**Pull request by Lkleindesigns**

### CODE REVIEW

**Review by draco-malfoy — CHANGES_REQUESTED** [review]
kindly update the link to "Dev" in company_database file. It leads to a different place

**Comment by Lkleindesigns** [comment]
Done, thank you!

**Review by draco-malfoy — CHANGES_REQUESTED** [review]
The link should lead to the company's separate file named as _company_name.md_ ,  in this case to the URL of _Dev.md_ in your forked repo. Please update this.

**Comment by Lkleindesigns** [comment]
Understood and corrected, sorry about that!

**Comment by draco-malfoy** [comment]
Sorry for the inconvenience caused. The files have been reorganized for better management. Kindly raise a separate PR adhering to these changes and we would be happy to review it. Thank you.

**Pull request closed without merging**
